#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="${DIR:-$BLOCK_INSTANCE}"
DIR="${DIR:-$HOME}"
ALERT_LOW="${ALERT_LOW:-$1}"
ALERT_LOW="${ALERT_LOW:-10}" # color will turn red under this value (default: 10%)
BAR_COLOR="${BAR_COLOR:-black}"
NEXT_COLOR="${NEXT_COLOR:-black}"
TEXT_COLOR="${TEXT_COLOR:-white}"
ICON="${ICON:-}"

LOCAL_FLAG="-l"
if [ "$1" = "-n" ] || [ "$2" = "-n" ]; then
    LOCAL_FLAG=""
fi

DISK=$(df -h -P $LOCAL_FLAG "$DIR" | awk '
/\/.*/ {
	# full text
	print $4

	use=$5

	# no need to continue parsing
	exit 0
}
')

echo -e "<span color='${BAR_COLOR}' bgcolor='${NEXT_COLOR}'></span>\
<span color='${TEXT_COLOR}' bgcolor='${BAR_COLOR}'> ${ICON} ${DISK} </span>"

echo -e "<span color='${BAR_COLOR}' bgcolor='${NEXT_COLOR}'></span>\
<span color='${TEXT_COLOR}' bgcolor='${BAR_COLOR}'> ${ICON} ${DISK} </span>"
